## Exploratory Data Analysis

Use this notebook to get familiar with the datasets we have. There is 10 questions we need to answer during the EDA.


We shouldn't limit our EDA to these 10 questions. Let's be creative :).

In [11]:
import pandas as pd
import numpy as np

In [12]:
data = pd.read_csv('data/data.csv')

In [13]:
data.head()

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,...,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,no_name
0,2019-05-19,UA,UA_CODESHARE,UA,4617,AX,N17146,4617,11292,DEN,...,752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-05-19,UA,UA_CODESHARE,UA,4615,AX,N12145,4615,11292,DEN,...,752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-05-19,UA,UA_CODESHARE,UA,4614,AX,N14117,4614,11695,FLG,...,503,73.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,2019-05-19,UA,UA_CODESHARE,UA,4613,AX,N14117,4613,10627,BIS,...,516,71.0,0.0,0.0,0.0,17.0,NaN,NaN,NaN,NaN
4,2019-05-19,UA,UA_CODESHARE,UA,4612,AX,N846HK,4612,14730,SDF,...,286,5.0,0.0,0.0,0.0,119.0,NaN,NaN,NaN,NaN

In [19]:
data.shape

(10000, 42)

In [20]:
data.dtypes

fl_date                 object
mkt_unique_carrier      object
branded_code_share      object
mkt_carrier             object
mkt_carrier_fl_num       int64
op_unique_carrier       object
tail_num                object
op_carrier_fl_num        int64
origin_airport_id        int64
origin                  object
origin_city_name        object
dest_airport_id          int64
dest                    object
dest_city_name          object
crs_dep_time             int64
dep_time               float64
dep_delay              float64
taxi_out               float64
wheels_off             float64
wheels_on              float64
taxi_in                float64
crs_arr_time             int64
arr_time               float64
arr_delay              float64
cancelled                int64
cancellation_code       object
diverted                 int64
dup                     object
crs_elapsed_time         int64
actual_elapsed_time    float64
air_time               float64
flights                  int64
distance                 int64
carrier_delay          float64
weather_delay          float64
nas_delay              float64
security_delay         float64
late_aircraft_delay    float64
first_dep_time         float64
total_add_gtime        float64
longest_add_gtime      float64
no_name                float64
dtype: object

In [15]:
data.describe()

,mkt_carrier_fl_num,op_carrier_fl_num,origin_airport_id,dest_airport_id,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,...,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,no_name
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,9821.000000,9821.000000,9805.000000,9805.000000,9794.000000,...,10000.000000,2152.000000,2152.000000,2152.000000,2152.000000,2152.000000,101.000000,101.000000,101.000000,0.0
mean,2764.467500,2764.402300,12527.218000,12538.420900,1329.410300,1335.464209,14.383668,18.260887,1359.126568,1456.588115,...,710.478200,23.534851,5.654275,18.223048,0.049257,29.026487,1489.247525,61.178218,58.178218,NaN
std,1740.745596,1740.629036,1521.215983,1515.388093,485.703022,500.484137,59.579193,10.235720,502.916787,528.941486,...,561.881465,75.603886,50.199439,40.297020,0.937066,60.282797,533.523222,59.815783,51.417973,NaN
min,1.000000,1.000000,10135.000000,10135.000000,5.000000,2.000000,-34.000000,2.000000,1.000000,1.000000,...,45.000000,0.000000,0.000000,0.000000,0.000000,0.000000,217.000000,4.000000,4.000000,NaN
25%,990.000000,990.000000,11267.000000,11267.000000,921.500000,927.000000,-5.000000,12.000000,940.000000,1043.250000,...,319.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1045.000000,22.000000,22.000000,NaN
50%,3119.500000,3119.500000,12339.000000,12441.000000,1325.000000,1328.000000,-2.000000,16.000000,1342.000000,1452.000000,...,550.000000,0.000000,0.000000,4.000000,0.000000,1.000000,1600.000000,36.000000,36.000000,NaN
75%,4292.250000,4292.250000,13930.000000,13930.000000,1730.000000,1743.000000,9.000000,21.000000,1759.000000,1906.000000,...,925.000000,18.000000,0.000000,23.000000,0.000000,34.000000,2001.000000,88.000000,88.000000,NaN
max,6202.000000,6095.000000,16218.000000,16218.000000,2359.000000,2400.000000,1690.000000,180.000000,2400.000000,2400.000000,...,4962.000000,1690.000000,1053.000000,874.000000,24.000000,928.000000,2354.000000,325.000000,206.000000,NaN

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   fl_date              10000 non-null  object
 1   mkt_unique_carrier   10000 non-null  object
 2   branded_code_share   10000 non-null  object
 3   mkt_carrier          10000 non-null  object
 4   mkt_carrier_fl_num   10000 non-null  int64
 5   op_unique_carrier    10000 non-null  object
 6   tail_num             9928 non-null   object
 7   op_carrier_fl_num    10000 non-null  int64
 8   origin_airport_id    10000 non-null  int64
 9   origin               10000 non-null  object
 10  origin_city_name     10000 non-null  object
 11  dest_airport_id      10000 non-null  int64
 12  dest                 10000 non-null  object
 13  dest_city_name       10000 non-null  object
 14  crs_dep_time         10000 non-null  int64
 15  dep_time             9821 non-null   float64
 16  dep_delay            9821 non-null   float64
 17  taxi_out             9805 non-null   float64
 18  wheels_off           9805 non-null   float64
 19  wheels_on            9794 non-null   float64
 20  taxi_in              9794 non-null   float64
 21  crs_arr_time         10000 non-null  int64
 22  arr_time             9794 non-null   float64
 23  arr_delay            9775 non-null   float64
 24  cancelled            10000 non-null  int64
 25  cancellation_code    201 non-null    object
 26  diverted             10000 non-null  int64
 27  dup                  10000 non-null  object
 28  crs_elapsed_time     10000 non-null  int64
 29  actual_elapsed_time  9775 non-null   float64
 30  air_time             9775 non-null   float64
 31  flights              10000 non-null  int64
 32  distance             10000 non-null  int64
 33  carrier_delay        2152 non-null   float64
 34  weather_delay        2152 non-null   float64
 35  nas_delay            2152 non-null   float64
 36  security_delay       2152 non-null   float64
 37  late_aircraft_delay  2152 non-null   float64
 38  first_dep_time       101 non-null    float64
 39  total_add_gtime      101 non-null    float64
 40  longest_add_gtime    101 non-null    float64
 41  no_name              0 non-null      float64
dtypes: float64(19), int64(11), object(12)
memory usage: 3.2+ MB

#### **Task 1**: Test the hypothesis that the delay is from Normal distribution. and that **mean** of the delay is 0. Be careful about the outliers.

#### **Task 2**: Is average/median monthly delay different during the year? If yes, which are months with the biggest delays and what could be the reason?

#### **Task 3**: Does the weather affect the delay? 
Use the API to pull the weather information for flights. There is no need to get weather for ALL flights. We can choose the right representative sample. Let's focus on four weather types:
- sunny
- cloudy
- rainy
- snow.
Test the hypothesis that these 4 delays are from the same distribution. If they are not, which ones are significantly different?

#### **Task 4**: How taxi times changing during the day? Does higher traffic lead to bigger taxi times?

#### **Task 5**: What is the average percentage of delays that is already created before departure? (aka are arrival delays caused by departure delays?) Are airlines able to lower the delay during the flights?

#### **Task 6**: How many states cover 50% of US air traffic?

#### **Task 7**: Test the hypothesis whether planes fly faster when there is the departure delay?

#### **Task 8**: When (which hour) do most 'LONG', 'SHORT', 'MEDIUM' haul flights take off?

#### **Task 9**: Find the top 10 the bussiest airports. Does the biggest number of flights mean that the biggest number of passengers went through the particular airport? How much traffic do these 10 airports cover?

#### **Task 10**: Do bigger delays lead to bigger fuel comsumption per passenger? 
We need to do four things to answer this as accurate as possible:
- Find out average monthly delay per air carrier (monthly delay is sum of all delays in 1 month)
- Find out distance covered monthly by different air carriers
- Find out number of passengers that were carried by different air carriers
- Find out total fuel comsumption per air carrier.

Use this information to get the average fuel comsumption per passenger per km. Is this higher for the airlines with bigger average delays?